### PR TITLE
Handle common prefixes in variant alleles

### PR DESCRIPTION
**Pull request by ao508**
Signed-off-by: Angelica Ochoa <15623749+ao508@users.noreply.github.com>

### CODE REVIEW

**Review by inodb — COMMENTED** [review]
Thanks 🙏!

Could you elaborate what this tries to solve? I believe genome nexus annotation pipeline does this prefix normalization as well that's a common artifacts of VCF->MAF conversion. Not saying it shouldn't be in this script (prolly makes sense to do normalization before annotation). Just wondering if the goal of this script is basically to do all the normalization pre running annotation in the annotation pipeline?

**Comment by ao508** [comment]
Just based on the variants Tom had shared in issue #34 I noticed there were common prefixes that the standardization script didnt resolve so the script handles that now. I'm not sure if it will resolve all of the issues reported in #34 but it will at least address some

**Review by inodb — APPROVED** [review]
@ao508 sounds good! I'm just a bit worried about not capturing these corner cases as tests in some way. Can be done later, but prolly good to file some ticket in that case

Like currently as a reviewer it's really hard to verify whether this is working, because there is no example data in the repo

EDIT: filed a separate ticket for testing: https://github.com/genome-nexus/annotation-tools/issues/40

**Comment by inodb** [comment]
Nice this solve my issue #30 as well - Thank you!

**Pull request merged**
