### PR TITLE
Dockerize annotation tools

### PR DESCRIPTION
**Pull request by ruslan-forostianov**

### CODE REVIEW

**Comment by ruslan-forostianov** [comment]
@ao508 @sheridancbio @inodb @plukase @pieterlukasse Please have a look

**Review by inodb — COMMENTED** [review]
Thanks so much @ruslan-forostianov - that looks great to me!

I believe there are some wrapper scripts which wouldn't work (`annotation_suite_wrapper.sh `), since those call the genome-nexus-annotation-pipeline if I'm not mistaken. Could you clarify in the description/comments of the Dockerfile what functionality is supported through this image and which aren't? That will help clarify what use case you are trying to support.

I'm trying to get agreement with this PR as well: https://github.com/genome-nexus/genome-nexus/pull/633/files. In my mind both are useful. One provides the all in one image if you want to use the wrapper script, the other is leaner and provides a subset of the functionality. Long term we prolly want one approach, but that will require some changes to how the app works rather than the Docker setup

Thank you!

**Comment by ruslan-forostianov** [comment]
@inodb Thanks for the review!

Indeed, `annotation_suite_wrapper.sh` script relies on `annotation.jar` to be in the folder next with other python scripts. I am not providing it with the docker file neither. I will add a clarification to the Dockerfile.

Ah, I've not been aware about the other PR. Thanks for pointing out.

**Review by inodb — APPROVED** [review]
LGTM - thank you!

**Comment by inodb** [comment]
I've updated the description of the PR a bit, feel free to change

**Pull request merged**
